# Rule identifiers turned on by default to exclude from running.
disabled_rules:
    - trailing_whitespace
    - comment_spacing
    - orphaned_doc_comment
    - todo
    - unneeded_override

# Some rules are turned off by default, so you need to opt-in.
opt_in_rules:
    # Category: - Performance
    - empty_count
    - empty_string
    - empty_collection_literal
    - first_where
    - last_where
    # Category: - Idiomatic
    - force_unwrapping
    - fatal_error_message
    - toggle_bool
    - joined_default_parameter
    # Category: - Type Definition
    - convenience_type
    - redundant_type_annotation
    # Category: - Access Control & IB
    - private_action
    - private_outlet
    - modifier_order
    # Category: - Lint (coding mistakes)
    - identical_operands
    - overridden_super_call
    - prohibited_super_call

# Case-sensitive paths to ignore during linting. Takes precedence over `included`.
excluded:
    - Pods
    - Carthage

type_name:
    excluded: K

identifier_name:
    excluded:
        - r
        - g
        - b
        - a
        - id
        - ok

vertical_whitespace:
    max_empty_lines: 2
    
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    
function_body_length:
    warning: 300
    error: 500
    
function_parameter_count:
    warning: 6
    error: 8
    
type_body_length:
    warning: 300
    error: 500
    
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
    
cyclomatic_complexity:
    warning: 15
    error: 25

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)
reporter: "xcode"
