name: SwiftLint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/swiftlint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"

jobs:
  SwiftLint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run SwiftLint
        run: |
          swiftlint lint --quiet --reporter github-actions-logging
