name: SwiftLint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/swiftlint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:0.54.0

    steps:
      - uses: actions/checkout@v4
      - name: Run SwiftLint v0.54.0
        run: swiftlint lint --quiet --reporter github-actions-logging
